default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 host: localhost
development:
 <<: *default
 database: blogger_development
 username: postgres
 password: postgres

test:
 <<: *default
 database: blogger_test
 username: postgres
 password: postgres

production:
  <<: *default
  database: blogger_production
  username: postgres
  password: postgres
