# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be07fa398f7daaa33fc521a29d84ffb1a297e72d950715c4256cd777673008414786b896e6e7f7d34869dafc6b84c0468107a8eb3830ae3f517e2ff74f336116
  gmail_email: bloomingshelf89609@gmail.com
  gmail_pass: passwordqwe
  instagram_client_id: 1b7d87b7c5af4524b35f8c9f2f6dd7b6
  instagram_secret: 2f7b8516043044d4bda0d6dc727cab89
  instagram_token:
test:
  secret_key_base: 8285ef3c7ad063d76c4900d35662fd2102c38c0e465c3a35c8ab6be2323a466ac2ad0a52c5d4e2b51ec6150a14b99d627a6882c5a8cdf5e532da220cbfdee0d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmail_email: bloomingshelf89609@gmail.com
  gmail_pass: passwordqwe
  instagram_client_id: 1b7d87b7c5af4524b35f8c9f2f6dd7b6
  instagram_secret: 2f7b8516043044d4bda0d6dc727cab89
  instagram_token:
